apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-soci-builder.fullname" . }}-service
  labels:
    {{- include "eks-soci-builder.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "eks-soci-builder.annotations" . | nindent 4 }}
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "eks-soci-builder.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}
