locals {
  k3s_token = "kimberly3sprang2cake4erm4DEBRIS"

  soci_setup = <<-EOT
    #!/bin/bash
    ARCH=$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
    VERSION=${var.soci_version}
    ARCHIVE=soci-snapshotter-$${VERSION}-linux-$${ARCH}.tar.gz

    curl -fLo $${ARCHIVE} https://github.com/awslabs/soci-snapshotter/releases/download/v$${VERSION}/$${ARCHIVE}
    curl -fLo $${ARCHIVE}.sha256sum https://github.com/awslabs/soci-snapshotter/releases/download/v$${VERSION}/$${ARCHIVE}.sha256sum
    sha256sum ./$ARCHIVE.sha256sum
    tar xzvf $${ARCHIVE} -C /usr/local/bin soci-snapshotter-grpc
    rm -rf $${ARCHIVE}
    rm -rf $${ARCHIVE}.sha256sum

    mkdir -p /etc/soci-snapshotter-grpc
    cat <<EOF_SNAPSHOTTER_CONFIG >/etc/soci-snapshotter-grpc/config.toml
    [cri_keychain]
    enable_keychain = true
    image_service_path = "/run/k3s/containerd/containerd.sock"
    EOF_SNAPSHOTTER_CONFIG

    curl -fLo /etc/systemd/system/soci-snapshotter.service https://raw.githubusercontent.com/awslabs/soci-snapshotter/v$${VERSION}/soci-snapshotter.service
    systemctl daemon-reload
    systemctl enable --now soci-snapshotter
    systemctl start soci-snapshotter
  EOT

  kubelet_config = <<-EOT
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    imageServiceEndpoint: unix:///run/soci-snapshotter-grpc/soci-snapshotter-grpc.sock
  EOT

  containerd_config = <<-EOT
    {{- /* */ -}}
    # File generated by {{ .Program }}. DO NOT EDIT. Use config-v3.toml.tmpl instead.
    version = 3
    imports = [{{ filepathjoin .NodeConfig.Containerd.Template "config-v3.toml.d" "*.toml" | printf "%q" }}]
    root = {{ printf "%q" .NodeConfig.Containerd.Root }}
    state = {{ printf "%q" .NodeConfig.Containerd.State }}

    [grpc]
      address = {{ deschemify .NodeConfig.Containerd.Address | printf "%q" }}

    [proxy_plugins]
      [proxy_plugins.soci]
        type = "snapshot"
        address = "/run/soci-snapshotter-grpc/soci-snapshotter-grpc.sock"
        [proxy_plugins.soci.exports]
          root = "/var/lib/soci-snapshotter-grpc"

    [plugins]
      [plugins.'io.containerd.internal.v1.opt']
        path = {{ printf "%q" .NodeConfig.Containerd.Opt }}

      [plugins.'io.containerd.grpc.v1.cri']
        stream_server_address = "127.0.0.1"
        stream_server_port = "10010"

      [plugins.'io.containerd.cri.v1.runtime']
        enable_selinux = {{ .NodeConfig.SELinux }}
        enable_unprivileged_ports = {{ .EnableUnprivileged }}
        enable_unprivileged_icmp = {{ .EnableUnprivileged }}
        device_ownership_from_security_context = {{ .NonrootDevices }}

      {{ if .DisableCgroup}}
        disable_cgroup = true
      {{ end }}

      {{ if .IsRunningInUserNS }}
        disable_apparmor = true
        restrict_oom_score_adj = true
      {{ end }}

      [plugins.'io.containerd.cri.v1.images']
        snapshotter = "soci"
        # This line is required for containerd to send information about how to lazily load the image to the snapshotter
        disable_snapshot_annotations = false
        use_local_image_pull = true

        {{ with .NodeConfig.AgentConfig.PauseImage }}
        [plugins.'io.containerd.cri.v1.images'.pinned_images]
          sandbox = "{{ . }}"
        {{ end }}

      {{- if or .NodeConfig.AgentConfig.CNIBinDir .NodeConfig.AgentConfig.CNIConfDir }}
      [plugins.'io.containerd.cri.v1.runtime'.cni]
        {{ with .NodeConfig.AgentConfig.CNIBinDir }}bin_dirs = [{{ printf "%q" . }}]{{ end }}
        {{ with .NodeConfig.AgentConfig.CNIConfDir }}conf_dir = {{ printf "%q" . }}{{ end }}
      {{ end }}

      {{ if or .NodeConfig.Containerd.BlockIOConfig .NodeConfig.Containerd.RDTConfig }}
      [plugins.'io.containerd.service.v1.tasks-service']
        {{ with .NodeConfig.Containerd.BlockIOConfig }}blockio_config_file = {{ printf "%q" . }}{{ end }}
        {{ with .NodeConfig.Containerd.RDTConfig }}rdt_config_file = {{ printf "%q" . }}{{ end }}
      {{ end }}

      {{ with .NodeConfig.DefaultRuntime }}
      [plugins.'io.containerd.cri.v1.runtime'.containerd]
        default_runtime_name = "{{ . }}"
      {{ end }}

        [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"

        [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runc.options]
          SystemdCgroup = {{ .SystemdCgroup }}

        [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runhcs-wcow-process]
          runtime_type = "io.containerd.runhcs.v1"

        {{ range $k, $v := .ExtraRuntimes }}
        [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.'{{ $k }}']
          runtime_type = "{{$v.RuntimeType}}"
        {{ with $v.BinaryName}}
        [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.'{{ $k }}'.options]
          BinaryName = {{ printf "%q" . }}
          SystemdCgroup = {{ $.SystemdCgroup }}
        {{ end }}
        {{ end }}

      [plugins.'io.containerd.cri.v1.images'.registry]
        config_path = {{ printf "%q" .NodeConfig.Containerd.Registry }}

        {{ if .PrivateRegistryConfig }}
        {{ range $k, $v := .PrivateRegistryConfig.Configs }}
        {{ with $v.Auth }}
        [plugins.'io.containerd.cri.v1.images'.registry.configs.'{{ $k }}'.auth]
          {{ with .Username }}username = {{ printf "%q" . }}{{ end }}
          {{ with .Password }}password = {{ printf "%q" . }}{{ end }}
          {{ with .Auth }}auth = {{ printf "%q" . }}{{ end }}
          {{ with .IdentityToken }}identitytoken = {{ printf "%q" . }}{{ end }}
        {{ end }}
        {{ end }}
        {{ end }}

      {{ if eq .NodeConfig.AgentConfig.Snapshotter "stargz" }}
      {{ with .NodeConfig.AgentConfig.ImageServiceSocket }}
      [plugins.'io.containerd.snapshotter.v1.stargz']
        cri_keychain_image_service_path = {{ printf "%q" . }}

        [plugins.'io.containerd.snapshotter.v1.stargz'.cri_keychain]
          enable_keychain = true
      {{ end }}

        [plugins.'io.containerd.snapshotter.v1.stargz'.registry]
          config_path = {{ printf "%q" .NodeConfig.Containerd.Registry }}

        {{ if .PrivateRegistryConfig }}
        {{ range $k, $v := .PrivateRegistryConfig.Configs }}
        {{ with $v.Auth }}
        [plugins.'io.containerd.snapshotter.v1.stargz'.registry.configs.'{{ $k }}'.auth]
          {{ with .Username }}username = {{ printf "%q" . }}{{ end }}
          {{ with .Password }}password = {{ printf "%q" . }}{{ end }}
          {{ with .Auth }}auth = {{ printf "%q" . }}{{ end }}
          {{ with .IdentityToken }}identitytoken = {{ printf "%q" . }}{{ end }}
        {{ end }}
        {{ end }}
        {{ end }}
        {{ end }}

      {{ if eq .NodeConfig.AgentConfig.Snapshotter "nix" }}
      {{ with .NodeConfig.AgentConfig.ImageServiceSocket }}
      [plugins.'io.containerd.snapshotter.v1.nix']
        address = {{ printf "%q" . }}

        [plugins.'io.containerd.snapshotter.v1.nix'.image_service]
          enable = true
          containerd_address = {{ deschemify $.NodeConfig.Containerd.Address | printf "%q" }}

        [[plugins.'io.containerd.transfer.v1.local'.unpack_config]]
          platform = "linux/amd64"
          snapshotter = "nix"
          differ = "walking"

        [[plugins.'io.containerd.transfer.v1.local'.unpack_config]]
          platform = "linux/arm64"
          snapshotter = "nix"
          differ = "walking"
      {{ end }}
      {{ end }}

      {{ if .IsRunningInUserNS }}
      [plugins.'io.containerd.nri.v1.nri']
        disable = true
      {{ end }}
  EOT

  # Cloud-init script for the master node
  # Installs K3s server, creates a wrapper script for kubectl, and sets the token
  master_cloud_init = <<-EOT
    #cloud-config
    package_update: true
    package_upgrade: true
    write_files:
      - path: /usr/local/bin/k
        permissions: '0755'
        content: |
          #!/bin/sh
          sudo k3s kubectl "$@"
      - path: /usr/local/bin/soci-setup.sh
        permissions: '0755'
        content: |
          ${indent(6, local.soci_setup)}
      - path: /var/lib/rancher/k3s/agent/etc/kubelet.conf.d/99-soci-snapshotter.conf
        permissions: '0644'
        content: |
          ${indent(6, local.kubelet_config)}
      - path: /var/lib/rancher/k3s/agent/etc/containerd/config-v3.toml.tmpl
        permissions: '0644'
        content: |
          ${indent(6, local.containerd_config)}
    runcmd:
      - /usr/local/bin/soci-setup.sh
      - curl -sfL https://get.k3s.io | K3S_TOKEN=${local.k3s_token} sh -s - server --cluster-init --node-label "role=master"
  EOT

  worker_cloud_init = <<-EOT
    #cloud-config
    package_update: true
    write_files:
      - path: /usr/local/bin/soci-setup.sh
        permissions: '0755'
        content: |
          ${indent(6, local.soci_setup)}
      - path: /var/lib/rancher/k3s/agent/etc/kubelet.conf.d/99-soci-snapshotter.conf
        permissions: '0644'
        content: |
          ${indent(6, local.kubelet_config)}
      - path: /var/lib/rancher/k3s/agent/etc/containerd/config-v3.toml.tmpl
        permissions: '0644'
        content: |
          ${indent(6, local.containerd_config)}
    runcmd:
      - /usr/local/bin/soci-setup.sh
      - curl -sfL https://get.k3s.io | K3S_URL=https://${multipass_instance.master_node.ipv4[0]}:6443 K3S_TOKEN=${local.k3s_token} sh -s - agent --node-label "role=worker"
  EOT
}
